export const booksList = [
  {
    id: 1,
    bookNo: "B001",
    owner: { name: "John Smith", imageUrl: "https://via.placeholder.com/180" },
    status: true,
    price: 15.99,
  },
  {
    id: 2,
    bookNo: "B002",
    owner: { name: "Jane Doe", imageUrl: "https://via.placeholder.com/180" },
    status: false,
    price: 12.99,
  },
  {
    id: 3,
    bookNo: "B003",
    owner: {
      name: "Alice Johnson",
      imageUrl: "https://via.placeholder.com/180",
    },
    status: true,
    price: 10.99,
  },
  {
    id: 4,
    bookNo: "B004",
    owner: { name: "Bob Brown", imageUrl: "https://via.placeholder.com/180" },
    status: false,
    price: 8.99,
  },
  {
    id: 5,
    bookNo: "B005",
    owner: {
      name: "Charlie Davis",
      imageUrl: "https://via.placeholder.com/180",
    },
    status: true,
    price: 18.99,
  },
  {
    id: 6,
    bookNo: "B006",
    owner: { name: "Diana Evans", imageUrl: "https://via.placeholder.com/180" },
    status: false,
    price: 14.99,
  },
  {
    id: 7,
    bookNo: "B007",
    owner: {
      name: "Edward Wilson",
      imageUrl: "https://via.placeholder.com/180",
    },
    status: true,
    price: 11.99,
  },
  {
    id: 8,
    bookNo: "B008",
    owner: {
      name: "Fiona Harris",
      imageUrl: "https://via.placeholder.com/180",
    },
    status: false,
    price: 9.99,
  },
  {
    id: 9,
    bookNo: "B009",
    owner: { name: "George King", imageUrl: "https://via.placeholder.com/180" },
    status: true,
    price: 16.99,
  },
  {
    id: 10,
    bookNo: "B010",
    owner: {
      name: "Hannah Wright",
      imageUrl: "https://via.placeholder.com/180",
    },
    status: false,
    price: 13.99,
  },
  {
    id: 11,
    bookNo: "B011",
    owner: { name: "Ian Turner", imageUrl: "https://via.placeholder.com/180" },
    status: true,
    price: 19.99,
  },
  {
    id: 12,
    bookNo: "B012",
    owner: { name: "Jane Young", imageUrl: "https://via.placeholder.com/180" },
    status: false,
    price: 17.99,
  },
  {
    id: 13,
    bookNo: "B013",
    owner: { name: "Kevin Adams", imageUrl: "https://via.placeholder.com/180" },
    status: true,
    price: 14.99,
  },
  {
    id: 14,
    bookNo: "B014",
    owner: { name: "Laura Hill", imageUrl: "https://via.placeholder.com/180" },
    status: false,
    price: 11.99,
  },
  {
    id: 15,
    bookNo: "B015",
    owner: {
      name: "Michael Scott",
      imageUrl: "https://via.placeholder.com/180",
    },
    status: true,
    price: 15.99,
  },
  {
    id: 16,
    bookNo: "B016",
    owner: { name: "Nina Clark", imageUrl: "https://via.placeholder.com/180" },
    status: false,
    price: 12.99,
  },
  {
    id: 17,
    bookNo: "B017",
    owner: {
      name: "Oliver Lewis",
      imageUrl: "https://via.placeholder.com/180",
    },
    status: true,
    price: 18.99,
  },
  {
    id: 18,
    bookNo: "B018",
    owner: {
      name: "Paula Robinson",
      imageUrl: "https://via.placeholder.com/180",
    },
    status: false,
    price: 10.99,
  },
  {
    id: 19,
    bookNo: "B019",
    owner: {
      name: "Quentin Hall",
      imageUrl: "https://via.placeholder.com/180",
    },
    status: true,
    price: 13.99,
  },
  {
    id: 20,
    bookNo: "B020",
    owner: { name: "Rachel Lee", imageUrl: "https://via.placeholder.com/180" },
    status: false,
    price: 9.99,
  },
];
export const booksListAdmin = [
  {
    id: 1,
    author: "John Grisham",
    owner: { name: "John Smith", imageUrl: "https://via.placeholder.com/180" },
    category: "Fiction",
    status: true,
    bookName: "The Firm",
  },
  {
    id: 2,
    author: "Agatha Christie",
    owner: { name: "Jane Doe", imageUrl: "https://via.placeholder.com/180" },
    category: "Mystery",
    status: false,
    bookName: "Murder on the Orient Express",
  },
  {
    id: 3,
    author: "J.K. Rowling",
    owner: {
      name: "Alice Johnson",
      imageUrl: "https://via.placeholder.com/180",
    },
    category: "Fantasy",
    status: true,
    bookName: "Harry Potter and the Sorcerer's Stone",
  },
  {
    id: 4,
    author: "George Orwell",
    owner: { name: "Bob Brown", imageUrl: "https://via.placeholder.com/180" },
    category: "Dystopian",
    status: false,
    bookName: "1984",
  },
  {
    id: 5,
    author: "Harper Lee",
    owner: {
      name: "Charlie Davis",
      imageUrl: "https://via.placeholder.com/180",
    },
    category: "Fiction",
    status: true,
    bookName: "To Kill a Mockingbird",
  },
  {
    id: 6,
    author: "F. Scott Fitzgerald",
    owner: { name: "Diana Evans", imageUrl: "https://via.placeholder.com/180" },
    category: "Classic",
    status: false,
    bookName: "The Great Gatsby",
  },
  {
    id: 7,
    author: "J.R.R. Tolkien",
    owner: {
      name: "Edward Wilson",
      imageUrl: "https://via.placeholder.com/180",
    },
    category: "Fantasy",
    status: true,
    bookName: "The Hobbit",
  },
  {
    id: 8,
    author: "Mark Twain",
    owner: {
      name: "Fiona Harris",
      imageUrl: "https://via.placeholder.com/180",
    },
    category: "Classic",
    status: false,
    bookName: "The Adventures of Tom Sawyer",
  },
  {
    id: 9,
    author: "Jane Austen",
    owner: { name: "George King", imageUrl: "https://via.placeholder.com/180" },
    category: "Romance",
    status: true,
    bookName: "Pride and Prejudice",
  },
  {
    id: 10,
    author: "Ernest Hemingway",
    owner: {
      name: "Hannah Wright",
      imageUrl: "https://via.placeholder.com/180",
    },
    category: "Fiction",
    status: false,
    bookName: "The Old Man and the Sea",
  },
  {
    id: 11,
    author: "Dan Brown",
    owner: { name: "Ian Turner", imageUrl: "https://via.placeholder.com/180" },
    category: "Thriller",
    status: true,
    bookName: "The Da Vinci Code",
  },
  {
    id: 12,
    author: "Leo Tolstoy",
    owner: { name: "Jane Young", imageUrl: "https://via.placeholder.com/180" },
    category: "Classic",
    status: false,
    bookName: "War and Peace",
  },
  {
    id: 13,
    author: "Charles Dickens",
    owner: { name: "Kevin Adams", imageUrl: "https://via.placeholder.com/180" },
    category: "Classic",
    status: true,
    bookName: "A Tale of Two Cities",
  },
  {
    id: 14,
    author: "H.G. Wells",
    owner: { name: "Laura Hill", imageUrl: "https://via.placeholder.com/180" },
    category: "Science Fiction",
    status: false,
    bookName: "The War of the Worlds",
  },
  {
    id: 15,
    author: "Stephen King",
    owner: {
      name: "Michael Scott",
      imageUrl: "https://via.placeholder.com/180",
    },
    category: "Horror",
    status: true,
    bookName: "The Shining",
  },
  {
    id: 16,
    author: "Emily Brontë",
    owner: { name: "Nina Clark", imageUrl: "https://via.placeholder.com/180" },
    category: "Classic",
    status: false,
    bookName: "Wuthering Heights",
  },
  {
    id: 17,
    author: "Herman Melville",
    owner: {
      name: "Oliver Lewis",
      imageUrl: "https://via.placeholder.com/180",
    },
    category: "Adventure",
    status: true,
    bookName: "Moby-Dick",
  },
  {
    id: 18,
    author: "Louisa May Alcott",
    owner: {
      name: "Paula Robinson",
      imageUrl: "https://via.placeholder.com/180",
    },
    category: "Fiction",
    status: false,
    bookName: "Little Women",
  },
  {
    id: 19,
    author: "Arthur Conan Doyle",
    owner: {
      name: "Quentin Hall",
      imageUrl: "https://via.placeholder.com/180",
    },
    category: "Mystery",
    status: true,
    bookName: "The Adventures of Sherlock Holmes",
  },
  {
    id: 20,
    author: "Victor Hugo",
    owner: { name: "Rachel Lee", imageUrl: "https://via.placeholder.com/180" },
    category: "Classic",
    status: false,
    bookName: "Les Misérables",
  },
];
